name 'continuent-percona_repo'
version '0.1.5'
source 'https://github.com/continuent/continuent-percona_repo'
author 'Continuent'
license 'Apache 2.0'
summary 'Module for installing Percona repositories'
description 'Module for installing Percona repositories'
project_page 'https://github.com/continuent/continuent-percona_repo'
dependency 'puppetlabs/apt', '>= 1.4.0'
